Repository Microcervejaria/Microcervejaria-Alexa, pull requests merged in 2020-10, with the labels that each got.

#20 Editando Launch Request Handler com mensagem de boas vindas
  lambda/lambda_function.py
Labels: Intent

#22 Configurar help intent
  lambda/lambda_function.py
  skill-package/interactionModels/custom/pt-BR.json
Labels: Função Lambda, Intent

#23 Adiciona Cancel Intent
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#24 Adiciona Home Intent
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#25 Configura intent de listar receitas
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#26 Define intents de Listar receitas
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#27 Define intent de detalhar receita
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#29 Adiciona samples para começar alguma Receita
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#30 Adiciona Handler para listar receitas
  lambda/lambda_function.py
Labels: API, Função Lambda, História de Usuário

#34 Adicionando stop intent
  lambda/lambda_function.py
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#35 Handler/iniciar producao
  lambda/lambda_function.py
  skill-package/interactionModels/custom/pt-BR.json
Labels: Função Lambda

#36 Configuraração Intent de Iniciar Limpeza
  skill-package/interactionModels/custom/pt-BR.json
Labels: Intent

#42 Adiciona handler para detalhar receita
  lambda/lambda_function.py
Labels: API, Função Lambda, História de Usuário
